version: '2'

services:
  back:
    environment:
      - MYSQL_HOST=jdbc:mysql://db:3306/url_shortener
      - MYSQL_PASS=root
    build:
      context: back
      dockerfile: Dockerfile
    container_name: back
    ports:
      - "9000:9000"
  front:
    build:
      context: front
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "3000:3000"
    stdin_open: true
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d/:ro